--
-- File generated with SQLiteStudio v3.3.2 on Mon Mar 22 13:35:23 2021
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, username TEXT NOT NULL UNIQUE, password TEXT NOT NULL, email TEXT UNIQUE NOT NULL, dob DATE);

CREATE TABLE playlists (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, title TEXT NOT NULL, user_id INTEGER REFERENCES users (id) NOT NULL);

CREATE TABLE entries (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, playlist_id INTEGER REFERENCES playlists (id) NOT NULL, song_id INTEGER REFERENCES songs (id) NOT NULL);

CREATE TABLE songs (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, title TEXT NOT NULL, artist TEXT NOT NULL, genre TEXT NOT NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
